### ISSUE TITLE
Raw image in color

### ISSUE THREAD

**Issue by nschlos** [faceterteam/PayCards_iOS#11]
Hello I am new in Objective C programming and would like to retrieve the raw image in color.
If I use the result.image i get a grayscale image. The idea is that if I cannot get the card data at least have a picture of the card. Is this possible?

Thanks in advance
Nico

**Comment by vitkuzmenko** [comment]
Hello!
We update framework on this week for receiving coloured image.

But you can receive color image in cardImageDidExtract method in PayCardsRecognizerDelegate.mm line 246
if will be use source code https://github.com/faceterteam/PayCards_iOS_Source

**Comment by nschlos** [comment]
Updated the latest version from 20 Dec 2017 and still I can only see the image as black and white. I am using only the Framework. May I instantiate the PayCardsRecognizerPlatformDelegate but cannot reach the other PayCardsRecognizerDelegate. Can you please guide me?

**Comment by vitkuzmenko** [comment]
I fix it tomorrow.

**Comment by vitkuzmenko** [comment]
I was update pod to version 1.1.4. Please make `pod update`

**Comment by nschlos** [comment]
Thanks man! Works fine now!
