### ISSUE TITLE
How to remove "powered by pay.cards" from Camera

### ISSUE THREAD

**Issue by bashirsk** [faceterteam/PayCards_iOS#26]
Hi, does anyone know how i can remove this button "powered by pay.cards" from camera please.Can i do it by using the pod. If there is another way, how can i remove it. It works when i remove it from there other 'PayCards_iOS_Source' but not this repo. Thanks.

**Comment by nameleast2** [comment]
How do you remove it by using the pod?

**Comment by bashirsk** [comment]
You can't

**Comment by andi357** [comment]
Sure you can easily do that by just iterating over the `container`s subviews (recursively) and finding the first `UIButton` occurrence. This can then simply be removed. For example like that:

```
recognizerContainer.findFirstSubview(ofType: UIButton.self)?.removeFromSuperview()
```

To get it short like that you need that simple `UIView` extension which is useful anyway:

```
extension UIView {

    func findFirstSubview<T: UIView>(ofType: T.Type) -> T? {
        return recursiveSubviews.first(where: { $0 is T }) as? T
    }

    var recursiveSubviews: [UIView] {
        return subviews + subviews.flatMap { $0.recursiveSubviews }
    }
}
```  

Make sure to call this __after__ the preview has been initialized,  with `recognizer.startCamera()`.

**Comment by bashirsk** [comment]
Thanks
