### ISSUE TITLE
Modification rights

### ISSUE THREAD

**Issue by saitbnzl** [faceterteam/PayCards_iOS#28]
I have a confusion about modification rights of this library. We have a commercial project, currently is being developed with Flutter. 

I am intended to modify this library for our project. So far, I can see it runs recognition algorithm on device. But it shares the results with PayCards. My company doesn't want this. 

So, I'm planning to modify this library (I guess "dramatically"). It will work with Flutter. And probably we will only use the algorithm but nothing else in the library. Am I allowed to do this? I know it's licensed with MIT license but the Term of Services are confusing me. I would appreciate it if you can clarify this for me.

**Comment by tchernitski** [comment]
The library doesn't share any result to anyone. Check out code source PayCards_iOS_Source.

**Comment by saitbnzl** [comment]
That's good to know. So, looks like all open-sourced and free to modify. Anyways, I will close this issue. Thanks for this library :)
