### ISSUE TITLE
Framework build for deployment target 10.3

### ISSUE THREAD

**Issue by AndreyDefine** [faceterteam/PayCards_iOS#4]
dyld: Symbol not found: ___NSDictionary0__
  Referenced from: /private/var/mobile/Containers/Bundle/Application/35E3D01C-09D3-40D1-A14A-F41B1C5DF813/RoboForm.app/Frameworks/PayCardsRecognizer.framework/PayCardsRecognizer (which was built for iOS 10.3)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /private/var/mobile/Containers/Bundle/Application/35E3D01C-09D3-40D1-A14A-F41B1C5DF813/RoboForm.app/Frameworks/PayCardsRecognizer.framework/PayCardsRecognizer

**Comment by AndreyDefine** [comment]
We need iOS 8 support

**Comment by GopiK14** [comment]
Any solution for this?
 We can able to restrict "pay card" based on OS version on scan card screen but the app is not launching because of "Framework build for deployment target 10.3". Is there any solution? 

Thanks!

**Comment by vitkuzmenko** [comment]
I will update framework soon (today-tomorrow) for iOS 8 support.

**Comment by GopiK14** [comment]
Thanks (y)

**Comment by GopiK14** [comment]
Team, 

May I know the status of iOS 8 support?

Thanks

**Comment by vitkuzmenko** [comment]
Yes! Tomorrow morning (UTC)

**Comment by GopiK14** [comment]
Ok, Thanks for the Info!

**Comment by vitkuzmenko** [comment]
framework updated. use version 1.1.3 `pod update`

**Comment by GopiK14** [comment]
Ok Thanks (y). Will check.
