### ISSUE TITLE
It can not scan printed card number

### ISSUE THREAD

**Issue by RiuHDuo** [faceterteam/PayCards_iOS#45]
I find this sdk can not scan the bank card like this:
![d53f8794a4c27d1ec395cf581bd5ad6edcc438fe](https://user-images.githubusercontent.com/830134/81916464-6e235180-9606-11ea-8cbc-36ea4106169d.jpg)

**Comment by vitkuzmenko** [comment]
Hello! Yes. Framework can not recognize Unembossed digits and letters.
