### ISSUE TITLE
Customize

### ISSUE THREAD

**Issue by Vitalik13** [faceterteam/PayCards_iOS#7]
Can I change color for scan's view corners of the frames ?

**Comment by Vitalik13** [comment]
Your card scan really very fast! Thank you for the it! But I want have opportunity customize scanner view! Because green color is not best case for depend app! Please will add depended from tint color.

**Comment by tchernitski** [comment]
Thanks

We will. 

For now you can change png file PayCards_iOS_Source/PayCardsRecognizer/CardRecognizer/Resources/PortraitFrame.png
and
https://github.com/faceterteam/PayCards_iOS_Source/blob/3a340383da7b4874489b44a7ed2cee3dec2efb18/PayCardsRecognizer/CardRecognizer/WOEdgesWrapperView.m#L24

**Comment by Vitalik13** [comment]
Ok, thank you!
